### ISSUE TITLE
[FEATURE REQUEST] Add an option to use the build number from pubspec for the msix version

### ISSUE THREAD

**Issue by CaptainDario** [YehudaKremer/msix#123]
It would be nice if it was possible to include the build number in the msix version number.
For example:
if I set 
`version: 1.3.1+29 `
in pubspec.yaml
the msix version would become:
`1.3.1.29`

Maybe you could add switch/option like 
`include_build_number: True/False`

**Comment by YehudaKremer** [comment]
Hello @CaptainDario 

Thanks for your suggestion 👍 

Please read "Limitations" at https://github.com/YehudaKremer/msix/pull/107
and the track issue.

**Comment by CaptainDario** [comment]
@YehudaKremer dart allows for an arbitrary build number, but I think that it's not common for a flutter app to set the build number to smth else than an int. Because an android app is checked in the play store against its build number and it has to be an int.

**Comment by skyeskie** [comment]
It's definitely possible, but since the build is unstructured, it's not straightforward.

When I wrote the code for personal use (https://github.com/skyeskie/msix_config_version_match), it was structured so that it would update the MSIX version field based on the pubspec version.

- Two fields were required: the pubspec version and the msix_version.
- It was a manually run step in CI pipeline, and would update the version field to match.
- This made it **stateful**, and it would increase the 4th number based on the previous state

When I wrote the PR, it was no longer stateful (removing the `msix_version` field entirely) and I was no longer using it. So I just did the simple, straightforward option of forcing the 4th number to 0. If you wanted a new installer number, bump the patch number.

----

One key point is I was trying to keep it simple and predictable. The semver library I use (and the semver spec) is [pub_semver](https://pub.dev/packages/pub_semver). It allows for `Major.Minor.Patch-Pre+Build` with pretty much unrestricted input for pre and build.

- Pre and build are each matched as a regular expression
  - Pre: `r'(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'`
  - Build: `r'(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?'`
- The match is split by periods, with pure numbers stored as a number

Ignoring the pre section, these would all be considered valid:
- 1.0.0+2022-08-31
- 1.0.0+bar
- 1.0.0+123
- 1.0.0+12.3
- 1.0.0+2022.8.31.14.19

---

So the minimal option would be to take the build number if it
- Only contains one part
- The only part is an `int`

That could be handled with something along the lines of (**not tested**):
https://github.com/YehudaKremer/msix/blob/main/lib/src/configuration.dart#L347
```dart
      final pubspecVersion = Version.parse(yaml['version']);
      final useBuild = pubspecVersion.build.length == 1 && pubspecVersion.build.first is int;
      return [
        pubspecVersion.major,
        pubspecVersion.minor,
        pubspecVersion.patch,
        useBuild ? pubspecVersion.build : 0,
      ].join('.');
```

**Comment by YehudaKremer** [comment]
BTW, Flutter 3.3 is finally doing the same idea - taking the version number for the .exe file assembly version:
![image](https://user-images.githubusercontent.com/946652/187778890-2d7a25b4-dd56-4716-84b5-b6980ebd383c.png)
