### ISSUE TITLE
[BUG] Installation location goes to a random location under %LOCALAPPDATA%\Packages\

### ISSUE THREAD

**Issue by alexlyp** [YehudaKremer/msix#173]
### :information_source: Info

**Version: v3.7.0**

### :speech_balloon: Description

**Enter a description of your problem here.<br />
Any logs, error and assets you have that can help to find this bug.<br />
To run the tool with extended logs use the `-v` argument, for example: `flutter pub run msix:create -v`**
When running a built flutter app directly after `flutter build windows`, the "defaultAppDataDirectory is properly determined by the following: `Platform.environment.containsKey("LOCALAPPDATA").`  All app files are then put in the %LOCALAPPDATA%/<appname> directory as expected.  

But when using msix, after installing and launching the app data directory resolves to some strange path `%LOCALAPPDATA%\Packages\com.flutter.bruig_ywj3797wkq8tj`   And I believe when the --identity-name is populated in the msix_config it would be instead `%LOCALAPPDATA%\Packages\<identity-name>_ywj3797wkq8tj`.  So I'm unsure if this is a configuration in our app or if this is a bug within msix itself.
### :scroll: Pubspec.yaml

https://github.com/companyzero/bisonrelay/blob/master/bruig/flutterui/bruig/pubspec.yaml#L54-L61

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

**Comment by AriDevC** [comment]
Currently facing this. Any updates?

**Comment by YehudaKremer** [comment]
Hello

The `_ywj3797wkq8tj` (ID) part is added automatically by the MSIX installer,
its a part for the virtual tree installation concept  (see more [here](https://github.com/YehudaKremer/msix/wiki/Application-Folder-And-Files)).

So, after the Msix installation, all you app-context is located under virtual-file-system-tree path (in your case the tree called `..._ywj3797wkq8tj`),
and also the `LOCALAPPDATA` environment variable is under that.

Instead of using `LOCALAPPDATA` you can try work with `AppData`,
for example: `${Platform.environment['AppData']}\\my_app_name`.

You can also (if needed) access you app installation files under the `..._ywj3797wkq8tj` path,
like that: `${File(Platform.resolvedExecutable).parent.path}\\myAssets`

Example using both `AppData` and `Platform.resolvedExecutable` paths, can found in Shortcut File example: https://github.com/YehudaKremer/msix/wiki/How-To-Create-Desktop-Shortcut

**Comment by alexlyp** [comment]
@YehudaKremer appreciate the information.  

Would you happen to know what causes the  vitrual-file-system-tree path ( `... _ywj3797wkq8tj`) to change?  It had been consistent for quite some time but now it's resolving to something different after adding some signtool-options to my msix_config in pubspec.yaml

**Comment by alexlyp** [comment]
Was thinking that maybe it is related to us updating to a new code signing certificate from a new certificate authority.  Would that change the path @YehudaKremer ?  There is a possibility that the publisher value is slightly different, but I believe everything should be the same.

**Comment by YehudaKremer** [comment]
Hello @alexlyp 

The `_ywj3797wkq8tj` part is the "PublisherID" in the [Package Family Name](https://learn.microsoft.com/en-us/mem/configmgr/protect/deploy-use/find-a-pfn-for-per-app-vpn) (PFN) pattern:
`%Name%_%Version%_%Architecture%_%PublisherID%`

For example, my application [SmartWatchWidget](https://apps.microsoft.com/store/detail/smart-watch-widget/9MXP7B6Q4TQD) is installed on my pc with the name:
`48434KremerSoftware.SmartWatchWidget_1.7.2.0_x64__8gd1dywhy2v8a`

You can see [here](https://stackoverflow.com/a/21775215/4480046) more details on how the "ywj3797wkq8tj" represents the "PublisherID".

**Comment by alexlyp** [comment]
Ah that makes sense @YehudaKremer

Is it possiible to override the cert's subject and just set "publisher" in the msix-config ?  I've attempted to explicitly set it to match the previous cert's information, but appears that it gets overridden.

Thanks for the help.
