### ISSUE TITLE
[BUG] Installer made with msix:publish not working

### ISSUE THREAD

**Issue by azwalzaman** [YehudaKremer/msix#175]
### :information_source: Info

**Version: `v3.7.0`**

### :speech_balloon: Description

**After building an installer using `msix:publish`,  the installer gives me an "unable to parse error" when I try to run it. But the installers in the versions folder work fine (built with the same code)**.<br />

### :scroll: Pubspec.yaml

**msix_config:
      display_name: App Name
      certificate_path: msix/cert.pfx
      certificate_password: ******************* #Use your real password here
      logo_path: "images/logo.jpg"
      app_installer:
        publish_folder_path: msix
        hours_between_update_checks: 0
        automatic_background_task: true
        update_blocks_activation: true
        show_prompt: true
        force_update_from_any_version: false
      msix_version: 1.0.3.0**

**Comment by Levi-Lesches** [comment]
This is probably because the package is using an outdated schema for the generated `.appinstaller` file. @YehudaKremer I'd be happy to look into adding a PR for this

**Comment by YehudaKremer** [comment]
Hey

The problem was that we didn't support absolute-path in the  `app_installer -> publish_folder_path` config field.
I publish new version ([3.12.1](https://pub.dev/packages/msix/versions/3.12.1)) with a [fix](https://github.com/YehudaKremer/msix/commit/8016025655098c4a953bb23cf3de892ac91f6aa4#diff-58bb726ab4bd757fbbba80a3457a5429149a61ffa2bf86f72a4632c04728cd3e) for that.
