### ISSUE TITLE
[BUG] Cert: can not found driver?

### ISSUE THREAD

**Issue by jinfagang** [YehudaKremer/msix#181]
```
packing msix files...

Unhandled exception:
dir : 找不到驱动器。名为“Cert”的驱动器不存在。
```

it says can not found dirver, I didn't know any about dirver? I have installed my own pfx file on my PC

**Comment by YehudaKremer** [comment]
Please use the bug report template: https://github.com/YehudaKremer/msix/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by caiohamamura** [comment]
I think I get it, it is because I've installed the `Powershell Core` v7. So that may have messed up with the original PSModulePath that the regular `Powershell` also uses. If I change `powershell.exe` to `pwsh.exe` in:  https://github.com/YehudaKremer/msix/blob/ab1d4b24dba477265fec2f0a48ee4c00b3d316b5/lib/src/sign_tool.dart#L151 

Everything works! I don't know how to provide a solution to that issue tough, since it is not everybody who has the `pwsh.exe` installed.

**Comment by YehudaKremer** [comment]
Hello

@caiohamamura thanks you for research and the PR fix 👍 
i publish new version [3.13.3](https://pub.dev/packages/msix/versions/3.13.3) with the fix.
